// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../mysrc/hetima/signal/signalserver.js', ['hetima.signal.SignalServer'], ['hetima.signal.UserInfo']);
goog.addDependency('../../../mysrc/hetima/signal/userinfo.js', ['hetima.signal.UserInfo'], []);
goog.addDependency('../../../mysrc/hetima/util/arraybuilder.js', ['hetima.util.ArrayBuilder'], []);
goog.addDependency('../../../mysrc/hetima/util/arraybuilder_test.js', ['hetima.util.ArrayBuilderTest'], ['goog.testing.jsunit', 'hetima.util.ArrayBuilder']);
goog.addDependency('../../../mysrc/hetima/util/bdecode.js', ['hetima.util.Bdecode'], ['hetima.util.ArrayBuilder', 'hetima.util.Encoder']);
goog.addDependency('../../../mysrc/hetima/util/bencode.js', ['hetima.util.Bencode'], ['hetima.util.ArrayBuilder']);
goog.addDependency('../../../mysrc/hetima/util/bencode_test.js', ['hetima.util.BencodeTest'], ['goog.testing.jsunit', 'hetima.util.ArrayBuilder', 'hetima.util.Bdecode', 'hetima.util.Bencode']);
goog.addDependency('../../../mysrc/hetima/util/encoder.js', ['hetima.util.Encoder'], []);
goog.addDependency('../../../mysrc/hetima/util/encoder_test.js', ['hetima.util.EncoderTest'], ['goog.testing.jsunit', 'hetima.util.Encoder']);
goog.addDependency('../../../mysrc/hetima/util/uuid.js', ['hetima.util.UUID'], []);
goog.addDependency('../../../mysrc/hetima/util/uuid_test.js', ['hetima.util.UUIDTest'], ['goog.testing.jsunit', 'hetima.util.UUID']);
