// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../mysrc/hetima/util/arraybuilder.js', ['hetima.util.ArrayBuilder'], []);
goog.addDependency('../../../mysrc/hetima/util/arraybuilder_test.js', ['hetima.util.ArrayBuilderTest'], ['goog.testing.jsunit', 'hetima.util.ArrayBuilder']);
goog.addDependency('../../../mysrc/hetima/util/uuid.js', ['hetima.util.UUID'], []);
goog.addDependency('../../../mysrc/hetima/util/uuid_test.js', ['hetima.util.UUIDTest'], ['goog.testing.jsunit', 'hetima.util.UUID']);
