// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../mysrc/hetima/util/uuid.js', ['hetima.util'], []);
goog.addDependency('../../../mysrc/hetima/util/uuid_test.js', ['hetima.util.UUIDTest'], ['goog.testing.jsunit', 'hetima.util']);
